MarvelApi_Mvc/Models/ViewModels/Team/CreateTeamViewModel.cs
using MarvelApi_Mvc.Models.DTOs.CharacterDTOs;
using MarvelApi_Mvc.Models.DTOs.TeamDTOs;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MarvelApi_Mvc.Models.ViewModels.Team
{
    public class CreateTeamViewModel
    {
        public TeamCreateDTO TeamCreateDTO { get; set; }
        public List<SelectListItem> AvailableCharacters { get; set; } = new List<SelectListItem>();
    }
}

MarvelApi_Mvc/Models/ViewModels/Team/UpdateTeamViewModel.cs
using MarvelApi_Mvc.Models.DTOs.TeamDTOs;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MarvelApi_Mvc.Models.ViewModels.Team
{
    public class UpdateTeamViewModel
    {
        public TeamUpdateDTO TeamUpdateDTO { get; set; }
        public List<SelectListItem> AvailableCharacters { get; set; } = new List<SelectListItem>();
    }
}

MarvelApi_Mvc/Controllers/AdminDashboardController.cs
using AutoMapper;
using MarvelApi_Mvc.Models;
using MarvelApi_Mvc.Models.DTOs.CharacterDTOs;
using MarvelApi_Mvc.Models.DTOs.TeamDTOs;
using MarvelApi_Mvc.Models.ViewModels.Character;
using MarvelApi_Mvc.Models.ViewModels.Team;
using MarvelApi_Mvc.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace MarvelApi_Mvc.Controllers
{
    public class AdminDashboardController : Controller
    {
        private readonly ICharacterService _characterService;
        private readonly ITeamService _teamService;
        private readonly ISelectListItemGetters _selectListItemGetters;
        private readonly IMapper _autoMapper;

        public AdminDashboardController(ICharacterService character, ITeamService teamService, ISelectListItemGetters selectListItemGetters, IMapper autoMapper)
        {
            _teamService = teamService;
            _characterService = character;
            _selectListItemGetters = selectListItemGetters;
            _autoMapper = autoMapper;
        }

        public async Task<ActionResult> IndexAdminDashboard(){
            return View();
        }

        public async Task<ActionResult> IndexDashboardCharacters(string searchQuery)
        {
            CharactersManagementViewModel charactersManagementViewModel = new CharactersManagementViewModel();
            var apiResponse = await _characterService.SearchAsync<ApiResponse>(searchQuery);
            if (apiResponse != null && apiResponse.IsSuccess)
            {
                charactersManagementViewModel.Characters = JsonConvert.DeserializeObject<IEnumerable<CharacterDTO>>(Convert.ToString(apiResponse.Result));
                return View(charactersManagementViewModel);
            }
            return View();
        }

        public async Task<ActionResult> IndexDashboardTeams(string searchQuery)
        {
            TeamManagementViewModel teamManagementViewModel = new TeamManagementViewModel();
            var apiResponse = await _teamService.SearchAsync<ApiResponse>(searchQuery);
            if (apiResponse != null && apiResponse.IsSuccess)
            {
                teamManagementViewModel.Teams = JsonConvert.DeserializeObject<IEnumerable<TeamDTO>>(Convert.ToString(apiResponse.Result));
                return View(teamManagementViewModel);
            }
            return View();
        }

        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> CreateCharacter()
        {
            var availableCharacters = await _selectListItemGetters.GetAvailableCharactersAsync();
            var availableTeams = await _selectListItemGetters.GetAvailableTeamsAsync();

            CharacterCreateViewModel characterCreateVM = new CharacterCreateViewModel();
            characterCreateVM.CharacterCreateDTO = new CharacterCreateDTO();
            characterCreateVM.AvailableCharacters = availableCharacters;
            characterCreateVM.AvailableTeams = availableTeams;
            return View(characterCreateVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> CreateCharacter(CharacterCreateViewModel characterCreateViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var response = await _characterService.CreateAsync<ApiResponse>(characterCreateViewModel.CharacterCreateDTO);
                    if (response != null && response.IsSuccess)
                    {
                        return RedirectToAction(nameof(IndexDashboardCharacters));
                    }
                    else if (response == null)
                    {
                        ModelState.AddModelError(string.Empty, "Only admin is allowed to make this action");
                    }
                }

                var availableCharacters = await _selectListItemGetters.GetAvailableCharactersAsync();
                var availableTeams = await _selectListItemGetters.GetAvailableTeamsAsync();
                characterCreateViewModel.AvailableCharacters = availableCharacters;
                characterCreateViewModel.AvailableTeams = availableTeams;
                return View(characterCreateViewModel);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> UpdateCharacter(int id)
        {
            var availableCharacters = await _selectListItemGetters.GetAvailableCharactersAsync();
            var availableTeams = await _selectListItemGetters.GetAvailableTeamsAsync();
            var characterDTO = await _selectListItemGetters.GetCharacterAsync(id);

            var characterUpdateDTO = _autoMapper.Map<CharacterUpdateDTO>(characterDTO);

            CharacterUpdateViewModel characterUpdateVM = new CharacterUpdateViewModel();
            characterUpdateVM.CharacterUpdateDTO = characterUpdateDTO;
            characterUpdateVM.AvailableCharacters = availableCharacters;
            characterUpdateVM.AvailableTeams = availableTeams;
            return View(characterUpdateVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> UpdateCharacter(CharacterUpdateViewModel characterUpdateViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //if (characterUpdateViewModel.CharacterUpdateDTO.ImageFile != null)
                    //{
                    //    using (var memoryStream = new MemoryStream())
                    //    {
                    //        await characterUpdateViewModel.CharacterUpdateDTO.ImageFile.CopyToAsync(memoryStream);
                    //        characterUpdateViewModel.CharacterUpdateDTO.Image = memoryStream.ToArray();
                    //    }
                    //}

                    var response = await _characterService.UpdateAsync<ApiResponse>(characterUpdateViewModel.CharacterUpdateDTO);
                    if (response != null && response.IsSuccess)
                    {
                        return RedirectToAction(nameof(IndexDashboardCharacters));
                    }
                    else if (response == null)
                    {
                        ModelState.AddModelError(string.Empty, "Only admin is allowed to make this action");
                    }
                }

                var availableCharacters = await _selectListItemGetters.GetAvailableCharactersAsync();
                var availableTeams = await _selectListItemGetters.GetAvailableTeamsAsync();
                characterUpdateViewModel.AvailableTeams = availableTeams;
                characterUpdateViewModel.AvailableCharacters = availableCharacters;
                return View(characterUpdateViewModel);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteCharacter(int id)
        {
            var response = await _characterService.DeleteAsync<ApiResponse>(id);
            return RedirectToAction(nameof(IndexDashboardCharacters));
        }

        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> CreateTeam()
        {
            var availableCharacters = await _selectListItemGetters.GetAvailableCharactersAsync();

            var teamCreateViewModel = new CreateTeamViewModel();
            TeamCreateDTO teamCreateDTO = new TeamCreateDTO();
            teamCreateViewModel.AvailableCharacters = availableCharacters;
            teamCreateViewModel.TeamCreateDTO = teamCreateDTO;
            return View(teamCreateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> CreateTeam(CreateTeamViewModel teamCreateViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var response = await _teamService.CreateAsync<ApiResponse>(teamCreateViewModel.TeamCreateDTO);
                    if (response != null && response.IsSuccess)
                    {
                        return RedirectToAction(nameof(IndexDashboardTeams));
                    }
                    else if (response == null)
                    {
                        ModelState.AddModelError(string.Empty, "Only admin is allowed to make this action");
                    }
                }

                var availableCharacters = await _selectListItemGetters.GetAvailableCharactersAsync();
                teamCreateViewModel.AvailableCharacters = availableCharacters;
                return View(teamCreateViewModel);
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> UpdateTeam(int id)
        {
            var teamDTO = await _selectListItemGetters.GetTeamAsync(id);
            var teamUpdateDTO = _autoMapper.Map<TeamUpdateDTO>(teamDTO);
            var availableCharacters = await _selectListItemGetters.GetAvailableCharactersAsync();

            UpdateTeamViewModel teamUpdateViewModel = new UpdateTeamViewModel();
            teamUpdateViewModel.TeamUpdateDTO = teamUpdateDTO;
            teamUpdateViewModel.AvailableCharacters = availableCharacters;
            return View(teamUpdateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> UpdateTeam(UpdateTeamViewModel teamUpdateViewModel)
        {
            try
            {

MarvelApi_Mvc/Views/AdminDashboard/CreateCharacter.cshtml
@using MarvelApi_Mvc.Models.ViewModels.Character
@model CharacterCreateViewModel
<br />
<script src="~/js/jquery-3.6.3.min.js"></script>
<body>
    <section class="starting-section">
        <form asp-controller="AdminDashboard" asp-action="CreateCharacter" method="post"
        enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="custom-text-danger"></div>
            <div class="character-form-container">
                <div class="character-form-subcontainer">
                    <div class="character-form-container-header">
                        <h2>Create Character</h2>
                    </div>
                    <div class="character-form-container-header">
                        <h3>Information</h3>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Name"></label>
                        <input class="search-input" asp-for="CharacterCreateDTO.Name" placeholder="Iron Man"/>
                        <span asp-validation-for="CharacterCreateDTO.Name" class="custom-text-danger"></span>
                    </div>                                        
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Eyes"></label>
                        <input class="search-input" asp-for="CharacterCreateDTO.Eyes" placeholder="Blue" />
                        <span asp-validation-for="CharacterCreateDTO.Eyes" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Weight"></label>
                        <input class="search-input" asp-for="CharacterCreateDTO.Weight" placeholder="84" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.Weight" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Height"></label>
                        <input class="search-input" asp-for="CharacterCreateDTO.Height" placeholder="178" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.Height" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label>Powers</label>
                        <textarea class="search-input search-input-textbox" asp-for="CharacterCreateDTO.Powers" placeholder="360 Vision, Energy Blasts, Repulsor Rays..."></textarea>
                        <span asp-validation-for="CharacterCreateDTO.Powers" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label>Hair Color</label>
                        <input class="search-input" asp-for="CharacterCreateDTO.Hair" placeholder="Black" />
                        <span asp-validation-for="CharacterCreateDTO.Hair" class="custom-text-danger"></span>
                    </div>                    
                    <div class="character-form-container-checkbox mt-2">
                        <input class="search-input search-input-checkbox" type="checkbox" asp-for="CharacterCreateDTO.IsVillain" />
                        <label>Villain</label>
                    </div>
                </div>
                <div class="character-form-subcontainer">
                    <div class="character-form-container-header">
                        <h3>Story</h3>
                    </div>
                    <div class="character-form-container-box">
                        <label>Place of origin</label>
                        <input class="search-input" asp-for="CharacterCreateDTO.Origin" placeholder="Long Island, New York" />
                        <span asp-validation-for="CharacterCreateDTO.Origin" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label>First Appearence Year</label>
                        <input class="search-input" asp-for="CharacterCreateDTO.FirstAppearanceYear" placeholder="Blue" />
                        <span asp-validation-for="CharacterCreateDTO.Eyes" class="custom-text-danger"></span>
                    </div>                    
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Appearance"></label>
                        <textarea class="search-input search-input-textbox" asp-for="CharacterCreateDTO.Appearance" placeholder="Iron Man 1, Iron Man 2, Avengers: Infinity War..."></textarea>
                        <span asp-validation-for="CharacterCreateDTO.Appearance" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label>Biography</label>
                        <textarea class="search-input search-input-textbox" asp-for="CharacterCreateDTO.Backstory" placeholder="Tony Stark is the wealthy son of industrialist and weapons manufacturer Howard Stark..."></textarea>
                        <span asp-validation-for="CharacterCreateDTO.Backstory" class="custom-text-danger"></span>
                    </div>
                </div>
                <div class="character-form-subcontainer">
                    <div class="character-form-container-header">
                        <h3>Statistics</h3>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Durability"></label>
                        <input type="number" class="search-input" asp-for="CharacterCreateDTO.Durability" placeholder="5" max="10" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.Durability" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Energy"></label>
                        <input type="number" class="search-input" asp-for="CharacterCreateDTO.Energy" placeholder="3" max="10" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.Energy" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label>Fighting Skills</label>
                        <input type="number" class="search-input" asp-for="CharacterCreateDTO.FightingSkills" placeholder="4" max="10" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.FightingSkills" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Strength"></label>
                        <input type="number" class="search-input" asp-for="CharacterCreateDTO.Strength" placeholder="4" max="10" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.Strength" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Intelligence"></label>
                        <input type="number" class="search-input" asp-for="CharacterCreateDTO.Intelligence" placeholder="8" max="10" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.Intelligence" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Speed"></label>
                        <input type="number" class="search-input" asp-for="CharacterCreateDTO.Speed" placeholder="6" max="10" min="0" />
                        <span asp-validation-for="CharacterCreateDTO.Speed" class="custom-text-danger"></span>
                    </div>
                </div>
                <div class="character-form-subcontainer">
                    <div class="character-form-container-header">
                        <h3>Connections</h3>
                    </div>
                    <div class="character-form-container-box col-span-2">
                        <label asp-for="CharacterCreateDTO.TeamId">Team</label>
                        <select class="search-input search-input-select" asp-for="CharacterCreateDTO.TeamId" asp-items="Model.AvailableTeams">
                            <option value="">Select a team</option>
                        </select>
                        <span asp-validation-for="CharacterCreateDTO.TeamId" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box"></div>
                    <div class="character-form-container-box col-span-2">
                        <label>Select Allies</label>
                        <select class="search-input searchable-dropdown" asp-for="CharacterCreateDTO.AllyIds" asp-items="Model.AvailableCharacters" multiple="multiple">
                        </select>
                        <span asp-validation-for="CharacterCreateDTO.AllyIds" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box col-span-2">
                        <label>Select Enemies</label>
                        <select class="search-input searchable-dropdown" asp-for="CharacterCreateDTO.EnemyIds" asp-items="Model.AvailableCharacters" multiple="multiple">
                        </select>
                        <span asp-validation-for="CharacterCreateDTO.EnemyIds" class="custom-text-danger"></span>
                    </div>
                </div>
                <div class="character-form-subcontainer subcontainer-image">
                    <div class="character-form-container-header">
                        <h3>Image</h3>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="CharacterCreateDTO.Image">Upload Image</label>
                        <input type="file" class="search-input lower-skew" asp-for="CharacterCreateDTO.Image" accept="image/*" onchange="previewImage(event)" />
                        <span asp-validation-for="CharacterCreateDTO.Image" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <img id="imagePreview" style="display:none" src="#" alt="Image Preview" />
                    </div>
                </div>
                <div class="character-form-subcontainer">
                    <div class="button-container-box col-span-2">
                        <button type="submit" class="btn-submit search-input-btn">Submit</button>
                        <a href="@Url.Action("IndexDashboardCharacters", "AdminDashboard")" class="btn-cancel search-input-btn">Cancel</a>
                    </div>
                </div>
            </div>
        </form>
    </section>
</body>

<script>
    $(document).ready(function () {
        $('.searchable-dropdown').select2({
            placeholder: "Select characters",
            allowClear: true,
            width: '100%'
        });
    });

    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('imagePreview');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

MarvelApi_Mvc/Views/AdminDashboard/CreateTeam.cshtml
@using MarvelApi_Mvc.Models.ViewModels.Team
@model CreateTeamViewModel
<br />
<script src="~/js/jquery-3.6.3.min.js"></script>
<body>
    <section class="starting-section">
        <form asp-controller="AdminDashboard" asp-action="CreateTeam" method="post"
              enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="custom-text-danger"></div>
            <div class="character-form-container">
                <div class="character-form-subcontainer">
                    <div class="character-form-container-header">
                        <h2>Create Team</h2>
                    </div>
                    <div class="character-form-container-header">
                        <h3>Information</h3>
                    </div>
                    <div class="character-form-container-box col-span-2">
                        <label asp-for="TeamCreateDTO.Name"></label>
                        <input class="search-input" asp-for="TeamCreateDTO.Name" placeholder="Avengers" />
                        <span asp-validation-for="TeamCreateDTO.Name" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box col-span-2">
                        <label>Description</label>
                        <textarea class="search-input search-input-textbox" asp-for="TeamCreateDTO.Description" placeholder="Earth's Mightiest Heroes stand as the planet's first line of defense against the most powerful..."></textarea>
                        <span asp-validation-for="TeamCreateDTO.Description" class="custom-text-danger"></span>
                    </div>
                </div>
                <div class="character-form-subcontainer">
                    <div class="character-form-container-header">
                        <h3>Connections</h3>
                    </div>
                    <div class="character-form-container-box col-span-2">
                        <label>Select Members</label>
                        <select class="search-input searchable-dropdown" asp-for="TeamCreateDTO.MemberIds" asp-items="Model.AvailableCharacters" multiple="multiple">
                        </select>
                        <span asp-validation-for="TeamCreateDTO.MemberIds" class="custom-text-danger"></span>
                    </div>
                </div>
                <div class="character-form-subcontainer subcontainer-image">
                    <div class="character-form-container-header">
                        <h3>Image</h3>
                    </div>
                    <div class="character-form-container-box">
                        <label asp-for="TeamCreateDTO.ImageForm">Upload Image</label>
                        <input type="file" class="search-input lower-skew" asp-for="TeamCreateDTO.ImageForm" accept="image/*" onchange="previewImage(event)" />
                        <span asp-validation-for="TeamCreateDTO.ImageForm" class="custom-text-danger"></span>
                    </div>
                    <div class="character-form-container-box">
                        <img id="imagePreview" style="display:none" src="#" alt="Image Preview" />
                    </div>
                </div>
                <div class="character-form-subcontainer">
                    <div class="button-container-box col-span-2">
                        <button type="submit" class="btn-submit search-input-btn">Submit</button>
                        <a href="@Url.Action("IndexDashboardTeams", "AdminDashboard")" class="btn-cancel search-input-btn">Cancel</a>
                    </div>
                </div>
            </div>
        </form>
    </section>
</body>

<script>
    $(document).ready(function () {
        $('.searchable-dropdown').select2({
            placeholder: "Select memebers",
            allowClear: true,
            width: '100%'
        });
    });

    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('imagePreview');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

MarvelApi_Mvc/Views/AdminDashboard/IndexAdminDashboard.cshtml
<section class="starting-section mt-5">
    <div class="admin-dashboard-header-container">
        <h2>Admin Dashboard</h2>
    </div>
    <div class="admin-dashboard-container">
        <a asp-controller="AdminDashboard" asp-action="IndexDashboardCharacters"
            class="admin-dashboard-box admin-dashboard-characters">
            <div class="overlay"></div>
            <h3 class="admin-dashboard-box-header">Characters</h3>
        </a>
        <a asp-controller="AdminDashboard" asp-action="IndexDashboardTeams"
            class="admin-dashboard-box admin-dashboard-teams">
            <div class="overlay"></div>
            <h3 class="admin-dashboard-box-header">Teams</h3>
        </a>
    </div>
</section>

MarvelApi_Mvc/Views/AdminDashboard/IndexDashboardCharacters.cshtml
@using MarvelApi_Mvc.Models.ViewModels.Character
@model CharactersManagementViewModel

<body>
    <section class="starting-section">
        <div class="main-container">
            <div class="container-header">
                <h2>Characters</h2>
            </div>
            <div class="filter-container">
                <div class="filter-container-search">
                    <form asp-controller="AdminDashboard" asp-action="IndexDashboardCharacters" method="get"
                          class="form-inline mb-4 justify-content-center">
                        <div class="filter-search">
                            <input type="text" name="searchQuery" class="search-input no-skew" aria-label="Search characters" placeholder="search">
                            <i class="fas fa-search search-icon"></i>
                        </div>
                    </form>
                </div>
                <div class="filter-container-buttons">
                    <a asp-controller="AdminDashboard" asp-action="CreateCharacter" class="btn-submit">New Character</a>
                </div>
            </div>
            <div class="item-container">
                <div class="characters-container-grid item-container-header">
                    <div class="optional-item"></div>
                    <div><h3>Id</h3></div>
                    <div><h3>Name</h3></div>
                    <div class="optional-item"><h3>Villain</h3></div>
                    <div></div>
                </div>
                @foreach (var character in Model.Characters)
                {
                    <div class="characters-container-grid item-container-items">
                        <div class="optional-item characters-img-container">
                            <img src="@character.ImageUrl" alt="comic-img" class="">
                        </div>
                        <div><h3>@character.Id</h3></div>
                        <div><h3>@character.Name</h3></div>
                        @if (character.IsVillain)
                        {
                            <div class="optional-item"><h3>Yes</h3></div>
                        }
                        else
                        {
                            <div class="optional-item"><h3>No</h3></div>
                        }
                        <div class="item-container-buttons">
                            <a asp-controller="AdminDashboard" asp-action="UpdateCharacter" asp-route-id="@character.Id" class="btn-edit"><i class="fa-solid fa-pen"></i></a>
                            <a asp-controller="AdminDashboard" asp-action="DeleteCharacter" asp-route-id="@character.Id" class="btn-cancel"><i class="fa-solid fa-trash"></i></a>
                        </div>
                    </div>
                }
            </div>
        </div>        
    </section>
</body>