MarvelApi_Mvc/Models/ViewModels/Home/HomeViewModel.cs
using MarvelApi_Mvc.Models.DTOs.CharacterDTOs;
using MarvelApi_Mvc.Models.DTOs.TeamDTOs;

namespace MarvelApi_Mvc.Models.ViewModels.Home
{
    public class HomeViewModel
    {
        public List<CharacterDTO> CharacterDTOs = new List<CharacterDTO>();
        public List<TeamDTO> TeamDTOs = new List<TeamDTO>();
    }
}

MarvelApi_Mvc/Controllers/CharacterController.cs
using MarvelApi_Mvc.Models;
using MarvelApi_Mvc.Models.DTOs.CharacterDTOs;
using MarvelApi_Mvc.Models.DTOs.TeamDTOs;
using MarvelApi_Mvc.Models.ViewModels.Character;
using MarvelApi_Mvc.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MarvelApi_Mvc.Controllers
{
    public class CharacterController : Controller
    {
        private readonly ICharacterService _characterService;

        public CharacterController(ICharacterService characterService)
        {
            _characterService = characterService;
        }

        public async Task<ActionResult> IndexCharacters(string searchQuery, int page = 1, int pageSize = 20)
        {
            ViewBag.PageSize = pageSize;
            ViewBag.CurrentPage = page;

            var allCharacters = new List<CharacterDTO>();
            var characters = new List<CharacterDTO>();

            var apiResponse = await _characterService.SearchAsync<ApiResponse>(searchQuery);
            if (apiResponse != null)
            {
                allCharacters = JsonConvert.DeserializeObject<IEnumerable<CharacterDTO>>(Convert.ToString(apiResponse.Result)).ToList();
            }

            if (allCharacters.Any())
                characters = allCharacters.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            var totalPages = (int)Math.Ceiling(allCharacters.Count() / (double)pageSize);

            var viewModel = new DisplayCharactersViewModel
            {
                CharacterDTOs = characters,
                TotalPages = totalPages,
                CurrentPage = page
            };

            return View(viewModel);
        }

        public async Task<ActionResult> IndexCharacter(int id)
        {
            DisplayCharacterViewModel characterVM = new DisplayCharacterViewModel();

			var characterTask = _characterService.GetAsync<ApiResponse>(id);
			var alliesTask = _characterService.GetAlliesAsync<ApiResponse>(id);
			var enemiesTask = _characterService.GetEnemiesAsync<ApiResponse>(id);
			var teamTask = _characterService.GetTeamAsync<ApiResponse>(id);

			await Task.WhenAll(characterTask, alliesTask, enemiesTask, teamTask);

			var characterResponse = await characterTask;
			var alliesResponse = await alliesTask;
			var enemiesResponse = await enemiesTask;
			var teamResponse = await teamTask;

			if (characterResponse != null && characterResponse.IsSuccess)
			{
				characterVM.Character = JsonConvert.DeserializeObject<CharacterDTO>(Convert.ToString(characterResponse.Result));
			}

			if (alliesResponse != null && alliesResponse.IsSuccess)
			{
				characterVM.Allies = JsonConvert.DeserializeObject<List<CharacterDTO>>(Convert.ToString(alliesResponse.Result));
			}

			if (enemiesResponse != null && enemiesResponse.IsSuccess)
			{
				characterVM.Enemies = JsonConvert.DeserializeObject<List<CharacterDTO>>(Convert.ToString(enemiesResponse.Result));
			}

			if (teamResponse != null && teamResponse.IsSuccess)
			{
				characterVM.Team = JsonConvert.DeserializeObject<TeamDTO>(Convert.ToString(teamResponse.Result));
			}

			return View(characterVM);
		}		
    }
}

MarvelApi_Mvc/Controllers/HomeController.cs
using MarvelApi_Mvc.Models;
using MarvelApi_Mvc.Models.DTOs.CharacterDTOs;
using MarvelApi_Mvc.Models.DTOs.TeamDTOs;
using MarvelApi_Mvc.Models.DTOs.UserDTOs;
using MarvelApi_Mvc.Models.ViewModels.Home;
using MarvelApi_Mvc.Services.IServices;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;

namespace MarvelApi_Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICharacterService _characterService;
        private readonly ITeamService _teamService;
        private readonly IMailReceiverService _emailReceiver;
        public HomeController(ICharacterService characterService, ITeamService teamService, ILogger<HomeController> logger,
            IMailReceiverService emailReceiver)
        {
            _characterService = characterService;
            _teamService = teamService;
            _logger = logger;
            _emailReceiver = emailReceiver;
        }

        public async Task<IActionResult> Index()
        {
            HomeViewModel homeViewModel = new();
            var characters = new List<CharacterDTO>();
            var apiResponse = await _characterService.GetAllAsync<ApiResponse>();
            if (apiResponse != null && apiResponse.IsSuccess)
            {
                characters = JsonConvert.DeserializeObject<IEnumerable<CharacterDTO>>(Convert.ToString(apiResponse.Result)).ToList();
            }
            var teams = new List<TeamDTO>();
            var response = await _teamService.GetAllAsync<ApiResponse>();
            if (response != null && response.IsSuccess)
            {
                teams = JsonConvert.DeserializeObject<IEnumerable<TeamDTO>>(Convert.ToString(response.Result)).ToList();
            }

            homeViewModel.CharacterDTOs = characters;
            homeViewModel.TeamDTOs = teams;
            return View(homeViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Contact(MailDTO mailDto)
        {
            await _emailReceiver.SendEmailAsync(mailDto);
            return Json(new { success = true });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarvelApi_Mvc/Controllers/TeamController.cs
using MarvelApi_Mvc.Models;
using MarvelApi_Mvc.Models.DTOs.CharacterDTOs;
using MarvelApi_Mvc.Models.DTOs.TeamDTOs;
using MarvelApi_Mvc.Models.ViewModels.Team;
using MarvelApi_Mvc.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;

namespace MarvelApi_Mvc.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamService _teamService;

        public TeamController(ITeamService teamService)
        {
            _teamService = teamService;
        }

        public async Task<ActionResult> IndexTeams(string searchQuery, int page = 1, int pageSize = 20)
        {
            ViewBag.PageSize = pageSize;
            ViewBag.CurrentPage = page;

            var allTeams = new List<TeamDTO>();
            var teams = new List<TeamDTO>();

            var apiResponse = await _teamService.SearchAsync<ApiResponse>(searchQuery);
            if (apiResponse != null && apiResponse.IsSuccess)
            {
                allTeams = JsonConvert.DeserializeObject<IEnumerable<TeamDTO>>(Convert.ToString(apiResponse.Result)).ToList();
            }

            if (allTeams.Any())
                teams = allTeams.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            var totalPages = (int)Math.Ceiling(allTeams.Count() / (double)pageSize);

            var viewModel = new DisplayTeamsViewModel
            {
                TeamDTOs = teams,
                CurrentPage = page,
                TotalPages = totalPages,
            };

            return View(viewModel);
        }

        public async Task<ActionResult> IndexTeam(int id)
        {
            DisplayTeamViewModel teamVM = new DisplayTeamViewModel();
            var apiResponse = await _teamService.GetAsync<ApiResponse>(id);
            if (apiResponse != null && apiResponse.IsSuccess)
            {
                var existingTeam = JsonConvert.DeserializeObject<TeamDTO>(Convert.ToString(apiResponse.Result));
                teamVM.Team = existingTeam;
            }

            apiResponse = await _teamService.GetMembersAsync<ApiResponse>(id);
			if (apiResponse != null && apiResponse.IsSuccess)
			{
				var existingMembers = JsonConvert.DeserializeObject<List<CharacterDTO>>(Convert.ToString(apiResponse.Result));
				teamVM.Members = existingMembers;
			}
			return View(teamVM);
        }
    }
}

MarvelApi_Mvc/Views/Home/About.cshtml
<br />
<body>
    <div class="container-fluid text-center text-white d-flex align-items-center justify-content-center
        flex-column hero-section about-section-main">
        <div class="overlay"></div>
        <div class="content overlay-txt">
            <h1 class="typing-text typing-text-faster">About</h1>
        </div>
        <div class="content">
            <p class="lead">
                MarvelAPI is your gateway to the Marvel Comics universe, offering detailed character profiles and exploring the connections between iconic heroes and villains. Built with cutting-edge .NET technologies, MarvelAPI provides an immersive experience for all Marvel fans.
            </p>
        </div>
    </div>
    <section class="about-section">
        <div class="about-section-container">
            <div class="about-section-box-header">
                <h2>Fullstack .NET Developer</h2>
            </div>
            <div class="about-section-box-empty">

            </div>
            <div class="about-section-box-info">
                <div class="about-section-box-img">
                    <img src="/images/marvel-characters-canvas.jpg" />
                </div>
                <div class="about-section-box-description">
                    <h3>Mislav Bučar</h3>
                    <p>I'm a passionate .NET developer with over two years of experience in building robust and scalable applications. My expertise lies in working with .NET technologies, including Blazor, MVC, and WPF. I have a solid understanding of both front-end and back-end development, and I enjoy creating dynamic and user-friendly applications.</p>
                    <p>Throughout my career, I've been involved in various projects, ranging from desktop applications to web solutions, and I've developed a deep appreciation for clean, maintainable code. I believe in continuous learning and am always exploring new technologies and methodologies to improve my skills and deliver the best results.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="project-section">
        <div class="project-section-container reverse-skew">
            <div class="project-section-box reverse-alignment">
                <h4 class="project-technology">C# | .NET | API | MVC</h4>
                <div class="project-section-box-header reverse">
                    <h2 class="project-name">MarvelApi(this)</h2>
                    <div class="project-line"></div>
                    <a href="https://github.com/MiBucar/MarvelApi"><i class="fa-solid fa-link project-link"></i></a>
                </div>
                <p class="project-description reverse-text reverse-text">MarvelAPI is a comprehensive web application that showcases a rich database of Marvel characters and teams through a self-developed API. The project leverages a robust MVC architecture to deliver a seamless and interactive user experience. By integrating the custom-built API, the application allows users to explore detailed profiles, team affiliations, and storylines, all while demonstrating the power and flexibility of .NET technologies.</p>
                <a href="https://github.com/MiBucar/MarvelApi" class="search-input-btn btn-discover reverse-skew">Discover</a>
            </div>
        </div>

        <div class="project-section-container">
            <div class="project-section-box">
                <h4 class="project-technology">C# | .NET | Blazor</h4>
                <div class="project-section-box-header">
                    <h2 class="project-name">Trendora Clothing Webstore</h2>
                    <div class="project-line"></div>
                    <a href="https://github.com/MiBucar/Trendora"><i class="fa-solid fa-link project-link"></i></a>
                </div>
                <p class="project-description">Project in Blazor which is deployed and running. Containing functionalities You would expect such a site to contain. Working with databases and clean code architecture. The project is made using Blazor server which in real case scenario would be a bad choice and I am aware of it, the reason for going with Blazor server is because I wanted to challenge myself and experience with SignalR. Everything about the project is listen on GitHub, as well as the documentation for it.</p>
                <a href="https://github.com/MiBucar/Trendora" class="search-input-btn btn-discover">Discover</a>
            </div>
        </div>

        <div class="project-section-container reverse-skew">
            <div class="project-section-box reverse-alignment">
                <h4 class="project-technology">C# | Unity</h4>
                <div class="project-section-box-header reverse">
                    <h2 class="project-name">NaNaglo</h2>
                    <div class="project-line"></div>
                    <a href="https://play.google.com/store/apps/details?id=com.MislavBucar.NaNaglo&pli=1"><i class="fa-solid fa-link project-link"></i></a>
                </div>
                <p class="project-description reverse-text reverse-text">This was my first project ever. The game is currenly on Google Play Store and it is a social game intended for people to hang out together and have a great time. It is only for the Balkans as it's on Croatian language only. </p>
                <a href="https://play.google.com/store/apps/details?id=com.MislavBucar.NaNaglo&pli=1" class="search-input-btn btn-discover reverse-skew">Discover</a>
            </div>
        </div>

        <div class="project-section-container">
            <div class="project-section-box">
                <h4 class="project-technology">C++</h4>
                <div class="project-section-box-header">
                    <h2 class="project-name">Breakout using SDL library</h2>
                    <div class="project-line"></div>
                    <a href="https://github.com/MiBucar/BreakoutSDL2"><i class="fa-solid fa-link project-link"></i></a>
                </div>
                <p class="project-description">Retro arcade game where you control the paddle and have a main goal of breaking every brick to proceed to the next level. The goal here was to create dynamic level creation, only files that have to be edited to change the brick layout or add new levels are .xml files. It also has changeable settings and a leaderboard.</p>
                <a href="https://github.com/MiBucar/BreakoutSDL2" class="search-input-btn btn-discover">Discover</a>
            </div>
        </div>

        <div class="project-section-container reverse-skew">
            <div class="project-section-box reverse-alignment">
                <h4 class="project-technology">C++</h4>
                <div class="project-section-box-header reverse">
                    <h2 class="project-name">Flappy Bird using SDL library</h2>
                    <div class="project-line"></div>
                    <a href="https://github.com/MiBucar/FlappyBird"><i class="fa-solid fa-link project-link"></i></a>
                </div>
                <p class="project-description reverse-text reverse-text">The goal of this project was creating a functional game without using an engine. It has functionalities such as changing volume in settings, a leaderboard and a fun gameplay where you play as a burger bird dodging dining tables instead of pipes.</p>
                <a href="https://github.com/MiBucar/FlappyBird" class="search-input-btn btn-discover reverse-skew">Discover</a>
            </div>
        </div>
    </section>
</body>

MarvelApi_Mvc/Views/Home/Index.cshtml
@using MarvelApi_Mvc.Models.ViewModels.Home
@model HomeViewModel

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>MarvelApi - Api Project for Marvel Heroes</title>
</head>

<body>
	<section id="banner">
		<div id="backtotop">
			<a href="#banner" id="backtotop-value"><i class="fa-solid fa-arrow-up"></i></a>
		</div>
		<div class="container zindex">
			<div class="row">
				<div class="col-lg-6 banner-txt">
					<span>The Ultimate</span>
					<h3>Marvel</h3>
					<h3 class="txt-pos">API.</h3>
					<div class="row banner-review">
						<div class="col-lg-3">
						</div>
						<div class="col-lg-4">
							<div class="stars">
							</div>
						</div>
					</div>
				</div>
				<div class="col-10 col-sm-11 col-md-7 col-lg-6 banner-images">
					<img src="/images/banner-icon.png" alt="banner-icon" class="banner-icon">
					<img src="/images/gray-characters.jpg" alt="banner-img" class="banner-img one img-fluid">
					<img src="/images/gray-characters-2.jpg" alt="banner-img" class="banner-img two img-fluid">
				</div>
			</div>
		</div>
	</section>

	@{
		int startYear = 2022;
		int currentYear = DateTime.Now.Year;
		int yearsOfExperience = currentYear - startYear;
	}

	<section id="about">
		<div class="container">
			<div class="row pt-5">
				<div class="col-lg-5 col-md-9 m-md-auto about-main">
					<img src="/images/portfolio-picture.jpg" alt="about-img" class="img-fluid">
					<div class="active-users">
						<h3 class="counter" data-counterup-time="2000" data-counterup-delay="30"
							data-counterup-beginat="1">5</h3><span>+</span>
						<p>Projects</p>
					</div>
					<div class="experience">
						<h3 class="counter" data-counterup-time="2000" data-counterup-delay="30"
							data-counterup-beginat="2">@yearsOfExperience</h3>
						<span>+</span>
						<p>Years of experience</p>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="about-txt">
						<span>About Me  |  Mislav bučar</span>
						<h3>Fullstack .NET developer</h3>
						<p class="pt-2 pb-4">@yearsOfExperience years of experience in
							building robust and scalable applications.
							My expertise lies in both backend and frontend technologies.</p>
						<div class="check-p">
							<p><i class="fa-solid fa-check"></i> Expertise in .NET Technologies</p>
							<p><i class="fa-solid fa-check"></i> Proficient in Backend and Frontend Development</p>
							<p><i class="fa-solid fa-check"></i> Passionate About Delivering Quality Solutions</p>
						</div>
						<a class="button-circular-2" href="https://github.com/MiBucar?tab=repositories"><i class="fa-brands fa-github"></i>
							Discover my work</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section id="team">
		<div class="container zindex">
			<div class="row">
				<div class="section-title t-white">
					<div class="row">
						<div class="col-lg-6">
							<span>The Project</span>
							<h3>Introduction.</h3>
						</div>
					</div>
				</div>
			</div>
			<div class="row align-items-center justify-content-around mb-5">
				<div class="col-lg-6 team-counter mb-4">
					<p class="pt-16">Welcome to MarvelApi, a web application bringing the Marvel comics universe to your
						fingertips.
						Utilizing cutting-edge .NET technologies, MarvelApi offers robust, scalable solutions with
						detailed information on Marvel characters via the
						Marvel Comics API, providing an immersive user experience.</p>
				</div>
				<div class="col-lg-3 col-md-6 team-item text-center">
					<div class="team-img">
						<img src="/images/marvel-logo.png" alt="team" class="img-fluid">
					</div>
				</div>
			</div>
			<div class="row team-counter-main">
				<div class="col-6 col-lg-3 team-counter">
					<p>Built with ASP.NET API and MVC</p>
				</div>
				<div class="col-6 col-lg-3 team-counter">
					<p>Utilizes Entity Framework Core for Data Management</p>
				</div>
				<div class="col-lg-6 col-lg-3 team-counter">
					<p>Frontend powered by Bootstrap and custom CSS</p>
				</div>
			</div>
		</div>
	</section>

	<section id="popular">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 section-title">
					<span>Popular</span>
					<h3>Explore Marvel Characters.</h3>
					<p>Explore detailed information, fascinating backstories, and stunning appearances of your favorite
						heroes and villains.</p>
					<a asp-controller="Character" asp-action="IndexCharacters" class="button-primary">Browse All</a>
				</div>
				@if (Model.CharacterDTOs.Any())
				{
					@for (int i = 0; i < Model.CharacterDTOs.Take(4).Count(); i++)
					{
						var character = Model.CharacterDTOs[i];
						<div class="col-lg-6 col-md-9 mobile-m-auto">
							<div class="popular-item @(i % 2 != 0 ? "right" : "") @(i == 3 ? "mb-0" : "")">
								<p>@character.FirstAppearanceYear</p>
								<div class="col-lg-10 @(i % 2 == 0 ? "ms-auto" : "me-auto")">
									<img src="@character.ImageUrl" alt="comic-book"
										 class="img-fluid">
									<a asp-controller="Character" asp-action="IndexCharacter" asp-route-id="@character.Id">@character.Name</a>
								</div>
							</div>
						</div>
					}
				}				
			</div>
		</div>
	</section>

	<section id="new-comics">
		<div class="container">
			<div class="row">
				<div class="section-title t-white">
					<div class="row">
						<div class="col-lg-6 m-auto text-center">
							<span>Popular</span>
							<h3>Explore most popular teams</h3>
							@if (!Model.TeamDTOs.Any())
							{
								<div class="team-counter mb-4">
									<p class="pt-16">
										No results
									</p>
								</div>
							}							
						</div>
					</div>
				</div>
			</div>
			<div class="row comic-item-pos">
				@if (Model.TeamDTOs.Any())
				{
					@for (int i = 0; i < Model.TeamDTOs.Take(3).Count(); i++)
					{
						var team = Model.TeamDTOs[i];
						<div class="col-lg-4 col-md-8 mobile-m-auto">
							<div class="comic-item @(i % 2 != 0 ? "active" : "")">
								<img src="@team.ImageUrl" alt="comic"
								class="img-fluid">
								<a class="veno-img" data-gall="comic1" href="@team.ImageUrl"><i class="fa-solid fa-plus"></i></a>
								<div class="comic-item-details">
									<div class="row">
										<div class="col-8 col-lg-8">
											<h3>@team.Name</h3>
										</div>
										<div class="col-4 col-lg-4 text-end">
											<a asp-action="IndexTeam" asp-controller="Team" asp-route-id="@team.Id"><i class="fa-solid fa-arrow-right"></i></a>
										</div>
									</div>
								</div>
							</div>
						</div>
					}
				}
				else
				{
					
				}
			</div>
		</div>
	</section>
</body>

</html>