MarvelApi_Mvc/ViewComponents/ContactFormViewComponent.cs
using MarvelApi_Mvc.Models.DTOs.UserDTOs;
using Microsoft.AspNetCore.Mvc;

namespace MarvelApi_Mvc.ViewComponents
{
    public class ContactFormViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var model = new MailDTO();
            return View(model);
        }
    }
}

MarvelApi_Mvc/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MarvelApi_Mvc.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

MarvelApi_Mvc/ViewComponents/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MarvelApi_Mvc.ViewComponents
{
    public class NavBarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

MarvelApi_Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarvelApi_Mvc</title>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarvelApi_Mvc.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/all.min.css" />
    <link rel="stylesheet" href="~/css/responsive.css" />
    <link rel="stylesheet" href="~/css/slick.css" />
    <link rel="stylesheet" href="~/css/venobox.min.css" />
    <link rel="stylesheet" href="~/css/animation.css" />
</head>

<body>    
    <div id="preloader">
        <div id="loading-center">
            <div id="loading-center-absolute">
                <div class="object" id="object_one"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_three"></div>
                <div class="object" id="object_four"></div>
            </div>
        </div>
    </div>

    @await Component.InvokeAsync("NavBar")
    @await Component.InvokeAsync("ContactForm")
    @RenderBody()
    @await Component.InvokeAsync("Footer")
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery-3.6.3.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/slick.min.js"></script>
    <script src="~/js/venobox.min.js"></script>
    <script src="~/js/counter.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/modalsubmission.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="https://kit.fontawesome.com/3b4a9fa9a2.js" crossorigin="anonymous"></script>        
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>